int connect(void);
int connectWithAddress(char usr_addr[18], int channel);
int disconnect(void);
int setJointZero(nxtJointId_t id);
int setJointZeros(void);
int moveJointContinuousNB(nxtJointId_t id, nxtJointState_t dir); 
int moveJointNB(nxtJointId_t id, int degrees);
int moveJointToNB(nxtJointId_t id, int angle);
int moveNB(int degrees1, int degrees2, int degrees3);
int moveToNB(int angle1, int angle2, int angle3);
int moveToZeroNB(void);
int moveJoint(nxtJointId_t id, int degrees);
int moveJointTo(nxtJointId_t id, int angle);
int move(int angle1, int angle2, int angle3);
int moveTo(int angle1, int angle2, int angle3);
int moveToZero(void);
int moveContinuousNB(nxtJointState_t dir1, nxtJointState_t dir2, nxtJointState_t dir3);
int moveContinuousTime(nxtJointState_t dir1, nxtJointState_t dir2, nxtJointState_t dir, int millSeconds);
int moveJointWait(nxtJointId_t id);
int moveWait(void);
int isConnected(void);
int isMoving(void);
int isJointMoving(nxtJointId_t id);
int getJointAngle(nxtJointId_t id, int *angle);
int getJointSpeedRatio(nxtJointId_t id, double *ratio);
int getJointSpeedRatios(double *ratio1, double *ratio2, double *ratio3);
int getJointState(nxtJointId_t id, int *status);
int stopOneJoint(nxtJointId_t id);
int stopTwoJoints(nxtJointId_t id1, nxtJointId_t id2);
int stopAllJoints(void);
int stopMotion(void);
int setSensor(nxtSensorId_t id, nxtSensorType_t type, nxtSensorMode_t mode);
int getSensor(nxtSensorId_t id, int *value);
int getJointStates(void);
int setJointSpeedRatio(nxtJointId_t id, double ratio);
int setJointSpeedRatios(double ratio1, double ratio2, double ratio3);
int vehicleMoveForwardNB(int angle);
int vehicleMoveBackwardNB(int angle);
int vehicleRotateLeftNB(int angle);
int vehicleRotateRightNB(int angle);
int vehicleMoveForward(int angle);
int vehicleMoveBackward(int angle);
int vehicleRotateLeft(int angle);
int vehicleRotateRight(int angle);
int vehicleMotionWait(void);
