//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by iMobotController_Windows.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_IMOBOTCONTROLLER_WINDOWS_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDI_ICON_up                     129
#define IDI_ICON_down                   130
#define IDI_ICON_stop                   131
#define IDB_BITMAP1                     132
#define IDB_BITMAP2                     133
#define IDI_ICON_right                  135
#define IDI_ICON_left                   136
#define IDD_DIALOG1                     138
#define IDD_DIALOG_CONFIG               138
#define IDR_MENU1                       139
#define IDI_ICON2                       147
#define IDI_ICON_GREENDOT               147
#define IDI_ICON3                       150
#define IDI_ICON_REDDOT                 153
#define IDR_MENU2                       154
#define IDR_MENU_RECORDEDMOTIONPOPUP    154
#define IDB_BITMAP7                     158
#define IDB_BITMAP_GENERAL              158
#define IDB_PNG_MACHINE                 159
#define IDB_PNG_HUMANOID                160
#define IDB_BITMAP_VEHICLE              163
#define IDB_BITMAP_MACHINE              163
#define IDB_PNG4                        164
#define IDB_BITMAP_HUMANOID             168
#define IDB_BITMAP8                     169
#define IDI_ICON4                       170
#define IDB_BITMAP6                     171
#define IDI_ICON_ch                     172
#define IDI_ICON5                       173
#define IDB_BITMAP9                     175
#define IDB_BITMAP_CH                   175
#define IDC_SLIDER_speed1               1000
#define IDC_EDIT_speed1                 1001
#define IDC_SLIDER_speed2               1002
#define IDC_EDIT_speed2                 1003
#define IDC_SLIDER_speed4               1004
#define IDC_EDIT_speed3                 1005
#define IDC_SLIDER_speed3               1006
#define IDC_EDIT_speed4                 1007
#define IDC_BUTTON_Motor1Forward        1008
#define IDC_BUTTON_Motor2Forward        1009
#define IDC_BUTTON_Motor3Forward        1010
#define IDC_BUTTON_Motor4Forward        1011
#define IDC_BUTTON_Motor1Stop           1012
#define IDC_BUTTON_Motor2Stop           1013
#define IDC_BUTTON_Motor3Stop           1014
#define IDC_BUTTON_Motor4Stop           1015
#define IDC_BUTTON_Motor1Backward       1016
#define IDC_BUTTON_Motor2Backward       1017
#define IDC_BUTTON_Motor3Backward       1018
#define IDC_BUTTON_Motor4Backward       1019
#define IDC_EDIT_position1              1020
#define IDC_EDIT_position2              1021
#define IDC_EDIT_position3              1022
#define IDC_EDIT_position4              1023
#define IDC_LIST_gaits                  1024
#define IDC_SLIDER_position1            1026
#define IDC_SLIDER_position2            1027
#define IDC_SLIDER_position3            1028
#define IDC_SLIDER_speed8               1029
#define IDC_SLIDER_position4            1029
#define IDC_BUTTON_connect              1031
#define IDC_BUTTON_rollLeft             1034
#define IDC_BUTTON_rollForward          1035
#define IDC_EDIT1                       1035
#define IDC_BUTTON_rollRight            1036
#define IDC_BUTTON1                     1036
#define IDC_BUTTON_ADD                  1036
#define IDC_BUTTON_rollStop             1037
#define IDC_LIST1                       1037
#define IDC_BUTTON_rollBack             1038
#define IDC_LIST2                       1038
#define IDC_BUTTON_MOVEUP               1039
#define IDC_BUTTON_MOVEDOWN             1040
#define IDC_BUTTON_REMOVE               1041
#define IDC_EDIT_setpos1                1042
#define IDC_EDIT_setpos2                1043
#define IDC_EDIT_setpos3                1044
#define IDC_EDIT_setpos4                1045
#define IDC_BUTTON2                     1046
#define IDC_BUTTON_GOPOS                1046
#define IDC_JOINTPICTURE                1047
#define IDC_BUTTON3                     1048
#define IDC_BUTTON_MOVETOZERO           1048
#define IDC_EDIT_setspd1                1049
#define IDC_EDIT_setspd2                1050
#define IDC_EDIT_setspd3                1051
#define IDC_EDIT_setspd4                1052
#define IDC_BUTTON_GOPOS2               1053
#define IDC_BUTTON_SETSPD               1053
#define IDC_BUTTON_MOVE                 1054
#define IDC_BUTTON4                     1066
#define IDC_BUTTON_SETZERO              1066
#define IDC_BUTTON_RESETTOZERO          1066
#define IDC_SPLIT_Sensor1Type           1068
#define IDC_SPLIT_Sensor2Type           1069
#define IDC_SPLIT_Sensor3Type           1070
#define IDC_SPLIT4                      1071
#define IDC_SPLIT_Sensor4Type           1071
#define IDC_EDIT2                       1072
#define IDC_EDIT_SensorValue1           1072
#define IDC_EDIT3                       1073
#define IDC_EDIT_SensorValue2           1073
#define IDC_EDIT4                       1074
#define IDC_EDIT_SensorValue3           1074
#define IDC_EDIT5                       1075
#define IDC_EDIT_SensorValue4           1075
#define IDC_COMBO_SENSORTYPE            1076
#define IDC_COMBO_Sensor1Type           1076
#define IDC_COMBO_Sensor2Type           1077
#define IDC_COMBO_Sensor3Type           1079
#define IDC_COMBO3                      1080
#define IDC_COMBO_Sensor4Type           1080
#define IDC_STATIC_GENERAL              1081
#define IDC_STATIC_VEHICLE              1082
#define IDB_STATIC_MACHINE              1083
#define IDC_STATIC_HUMANOID             1084
#define IDC_BUTTON5                     1085
#define IDC_BUTTON_rotateLeft           1085
#define IDC_BUTTON_portaStop            1086
#define IDC_BUTTON_rotateStop           1086
#define IDC_BUTTON_rotateRight          1087
#define IDC_BUTTON_walkForward          1088
#define IDC_BUTTON_walkStop             1089
#define IDC_BUTTON8                     1090
#define IDC_BUTTON_walkBackward         1090
#define IDC_BUTTON_moveArmUp            1091
#define IDC_BUTTON_armStop              1092
#define IDC_BUTTON_moveStop             1092
#define IDC_BUTTON_moveArmDown          1093
#define IDC_BUTTON_rotateArmLeft        1094
#define IDC_BUTTON_rotateArmRight       1095
#define IDC_RADIO_clawOpen              1097
#define IDC_RADIO_clawClose             1098
#define ID_ROBOT_CONFIGUREROBOTBLUETOOTH 32771
#define ID_ROBOT_CONNECTTOAROBOT        32772
#define ID_FILE                         32773
#define ID_CONNECT_DISCONNECTFROMROBOT  32774
#define ID_HELP_HELP                    32775
#define ID_HELP_ABOUTROBOTCONTROLLER    32776
#define ID_FILE_EXIT                    32777
#define ID_HELP_DEMOS                   32778
#define ID_TEACHINGMODE_TEACHINGMODEDIALOG 32779
#define ID_RENAME                       32780
#define ID_RENAME_REMOVE                32781
#define ID_RENAME_REMOVE32782           32782
#define ID_RECORDED_MOVEUP              32783
#define ID_RECORDED_MOVEDOWN            32784
#define ID_RECORDED_GOTOPOSE            32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        176
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
