#include <stdio.h>
#include "robotManager.h"
//#include "TeachingDialog.h"

RobotManager::RobotManager()
{
  int i;
  for(i = 0; i < MAX_CONNECTED; i++) {
    _connected[i] = false;
    _mobots[i] = NULL;
    _connectedAddresses[i] = NULL;
  }
}

RobotManager::~RobotManager()
{
}

bool RobotManager::isConnected(int index) {
  if((index >= numEntries()) || index < 0) {
    return false;
  }
  return _connected[index];
}

void RobotManager::setConnected(int index, bool connected)
{
  _connected[index] = connected;
}

int RobotManager::connect(int availableIndex)
{
  int i;
  int index;
  int err = 0;
  TCHAR name[80];
  swprintf(name, TEXT("robot%d"), numConnected()+1);
  CRecordMobot *mobot = new CRecordMobot(name);
  index = availableIndexToIndex(availableIndex);
  if(err = mobot->connectWithAddress( getEntry(index), 1 )) {
    return err;
  }
  /* Enable the button callback */
 // mobot->enableButtonCallback(CTeachingDialog::OnMobotButton);
  mobot->setJointSpeedRatios(1, 1, 1, 1);
  /* Insert the newly connected robot to the bottom of the list. */
  _mobots[numConnected()] = mobot;
  _connectedAddresses[numConnected()] = 
	  _addresses[availableIndexToIndex(availableIndex)];
  _connected[availableIndexToIndex(availableIndex)] = true;
  return err;
}

int RobotManager::disconnect(int connectIndex)
{
  int i;
  int foundEntry = 0;
  /* Need to find the ConfigFile index of the connected robot */
  for(i = 0; i < numEntries(); i++) {
    if(_connectedAddresses[connectIndex] == _addresses[i]) {
      foundEntry = 1;
      break;
    }
  }
  if(foundEntry == 0) { return -1; }
  _mobots[connectIndex]->disconnect();
  /* Need to shift addresses and mobots up */
  int j;
  for(j = connectIndex+1; j < numConnected(); j++) {
	_connectedAddresses[j-1] = _connectedAddresses[j];
	_mobots[j-1] = _mobots[j];
  }
  _connected[i] = false;
  return 0; 
}

int RobotManager::moveUp(int connectIndex) {
  CRecordMobot* tempMobot;
  char* tempAddr;
  if(connectIndex < 1 || connectIndex >= numConnected()) return -1;
  /* Swap the robot with the one prior */
  tempMobot = _mobots[connectIndex-1];
  tempAddr = _connectedAddresses[connectIndex-1];
  _mobots[connectIndex-1] = _mobots[connectIndex];
  _connectedAddresses[connectIndex-1] = _connectedAddresses[connectIndex];
  _mobots[connectIndex] = tempMobot;
  _connectedAddresses[connectIndex] = tempAddr;
  return 0;
}

int RobotManager::moveDown(int connectIndex) {
  CRecordMobot* tempMobot;
  char* tempAddr;
  if(connectIndex < 0 || connectIndex >= (numConnected()-1)) return -1;
  tempMobot = _mobots[connectIndex + 1];
  tempAddr = _connectedAddresses[connectIndex + 1];
  _mobots[connectIndex+1] = _mobots[connectIndex];
  _connectedAddresses[connectIndex+1] = _connectedAddresses[connectIndex];
  _mobots[connectIndex] = tempMobot;
  _connectedAddresses[connectIndex] = tempAddr;
  return 0;
}

int RobotManager::numConnected()
{
  int num = 0, i;
  for(i = 0; i < numEntries(); i++) {
    if(_connected[i]) {
      num++;
    }
  }
  return num;
}

const char* RobotManager::getConnected(int connectIndex) {
	if(connectIndex < 0 || connectIndex >= numConnected()) {
		return NULL;
	}
	return _connectedAddresses[connectIndex];
}

int RobotManager::availableIndexToIndex(int availableIndex)
{
	int index = 0;
	int i;
	if(availableIndex < 0 || availableIndex > numAvailable()) {
		return -1;
	}
	for(index = 0, i = 0; i <= availableIndex; index++) {
		if(_connected[index] == false) {
			i++;
		}
	}
	index--;
	return index;
}

int RobotManager::numAvailable()
{
	return numEntries() - numConnected();
}

CRecordMobot* RobotManager::getMobot(int connectIndex)
{
	if(connectIndex < 0 || connectIndex >= numConnected()) {
		return NULL;
	}
	return _mobots[connectIndex];
}

CString* RobotManager::generateProgram(bool looped)
{
  USES_CONVERSION;
  CString buf;
  CString *program = new CString();
  TCHAR tbuf[200];
  int i, j;
  *program += _T("/* Program generated by RobotController */\n");
  *program += _T("#include <mobot.h>\n\n");

  /* Declare the appropiate number of CMobot variables */
  for(i = 0; i < numConnected(); i++) {
    buf.Format(_T("CMobot robot%d;\n"), i+1);
    *program += buf;
  }

  /* Connect to each one */
  for(i = 0; i < numConnected(); i++) {
    buf.Format(_T("robot%d.connectWithAddress(\"%s\", 1);\n"),
       i+1,
      A2T(getMobot(i)->getAddress()) );
    *program += buf;
  }

  if(looped) {
    *program += _T("/* Set the \"num\" variable to the number of times to loop. */\n");
    *program += _T("int num = 3;\n");
    *program += _T("int i;\n");
    *program += _T("for(i = 0; i < num; i++) {");
  }
  /* Now go through each motion */
  for(i = 0; i < getMobot(0)->numMotions(); i++) {
    *program += _T("\n");
    /* First, print the comment for the motion */
    buf.Format(_T("/* %s */\n"), getMobot(0)->getMotionName(i));
    if(looped) *program += _T("    ");
    *program += buf;
    /* Now, print each robots motion */
    for(j = 0; j < numConnected(); j++) {
      getMobot(j)->getMotionString(i, tbuf);
      buf.Format(_T("%s\n"), tbuf);
      if(looped) *program += _T("    ");
      *program += buf;
      if(getMobot(j)->getMotionType(i) == MOTION_SLEEP) {
        break;
      }
    }
    /* Make sure all the robots are done moving */
    for(j = 0; j < numConnected(); j++) {
      if(getMobot(j)->getMotionType(i) == MOTION_SLEEP) {
        break;
      }
      buf.Format(_T("robot%d.moveWait();\n"), j+1);
      if(looped) *program += _T("    ");
      *program += buf;
    }
  }
  if(looped) {
    *program += _T("}\n");
  }
  return program;
}
